title: Obsidian Math Booster

theme: minima

header_pages:
  - math-callouts.md
  - equation-number.md
  - proofs.md
  - suggest.md
  - backlinks.md
  - cleveref.md
  - math-preview.md
  - context-settings.md
  - profiles.md
  - style-your-theorems.md
  - mathlinks.md
  - tips.md

github_username: RyotaUshio
