title: Obsidian Mathematics
theme: minima
header_pages:
  - math-callouts.md
  - equation-number.md
  - math-preview.md
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/RyotaUshio/obsidian-math" }
  
