title: Obsidian Math Booster

theme: minima

header_pages:
  - math-callouts.md
  - equation-number.md
  - proofs.md
  - suggest.md
  - backlinks.md
  - math-preview.md
  - style-your-theorems.md
  - tips.md

github_username: RyotaUshio
